#!/usr/bin/env lua

local map 	= require("mapping")
local cmd 	= require("cmd")
local flags	= require("flags")
flags.Get(arg)

_G["RESULT"] = ""

function Globalize(var)
	for k, v in pairs(var) do _G[k] = v end
end

Globalize(map)
Globalize(cmd)

local PATH = "/home/andy/.config/openbox/lxde-rc.xml"
local DEFAULT = "default.xml"

local file, err = io.open(DEFAULT, "r")
if not file then
	print("Failed opening file: " .. err)
	return 1
end

local content = file:read("*a")
file:close()

require("binds")

content = content:gsub("</keyboard>", RESULT .. "\n</keyboard>", 1)

file = io.open(PATH, "w")
file:write(content)
file:close()

os.execute("openbox --reconfigure")

print("Binds were set successfully.")

