
-- Numpad
_G.NP_0 = "KP_0"
_G.NP_1 = "KP_1"
_G.NP_2 = "KP_2"
_G.NP_3 = "KP_3"
_G.NP_4 = "KP_4"
_G.NP_5 = "KP_5"
_G.NP_6 = "KP_6"
_G.NP_7 = "KP_7"
_G.NP_8 = "KP_8"
_G.NP_9 = "KP_9"
_G.NP_Add = "KP_Add"
_G.NP_Subtract = "KP_Subtract"
_G.NP_Multiply = "KP_Multiply"
_G.NP_Divide = "KP_Divide"
_G.NP_Decimal = "KP_Decimal"
_G.NP_Enter = "KP_Enter"
_G.NP_Home = "KP_Home"
_G.NP_End = "KP_End"
_G.NP_Up = "KP_Up"
_G.NP_Down = "KP_Down"
_G.NP_Left = "KP_Left"
_G.NP_Right = "KP_Right"
_G.NP_PageUp = "KP_Page_Up"
_G.NP_PageDown = "KP_Page_Down"
_G.NP_Insert = "KP_Insert"
_G.NP_Delete = "KP_Delete"

_G.SUPER   = "W"
_G.SHIFT   = "S"
_G.CONTROL = "C"
_G.ALT     = "A"

_G.ENTER      = "Return"
_G.ESCAPE     = "Escape"
_G.TAB        = "Tab"
_G.SPACE      = "space"
_G.BACKSPACE  = "BackSpace"
_G.DELETE     = "Delete"
_G.INSERT     = "Insert"

_G.UP         = "Up"
_G.DOWN       = "Down"
_G.LEFT       = "Left"
_G.RIGHT      = "Right"
_G.HOME       = "Home"
_G.END        = "End"
_G.PAGE_UP    = "Page_Up"
_G.PAGE_DOWN  = "Page_Down"

_G.F1  = "F1"
_G.F2  = "F2"
_G.F3  = "F3"
_G.F4  = "F4"
_G.F5  = "F5"
_G.F6  = "F6"
_G.F7  = "F7"
_G.F8  = "F8"
_G.F9  = "F9"
_G.F10 = "F10"
_G.F11 = "F11"
_G.F12 = "F12"

_G.VOLUME_UP     = "XF86AudioRaiseVolume"
_G.VOLUME_DOWN   = "XF86AudioLowerVolume"
_G.VOLUME_MUTE   = "XF86AudioMute"
_G.MEDIA_PLAY    = "XF86AudioPlay"
_G.MEDIA_PAUSE   = "XF86AudioPause"
_G.MEDIA_STOP    = "XF86AudioStop"
_G.MEDIA_NEXT    = "XF86AudioNext"
_G.MEDIA_PREV    = "XF86AudioPrev"

_G.PRINT_SCREEN = "Print"
_G.MENU         = "Menu"

_G.CLICK = "Click"
_G.DRAG = "Drag"
_G.PRESS = "Press"
_G.DOUBLE_CLICK = "DoubleClick"

-- Context Names
_G.CONTEXT_FRAME = "Frame"
_G.CONTEXT_TITLEBAR = "Titlebar"
_G.CONTEXT_TOP = "Top"

